services:

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: django
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - .env


volumes:
  data: